TITLE hodgkin_huxley_Leak


COMMENT
This file was generated by NEMO (http://wiki.call-cc.org/nemo) version 9.0 on Mon Sep 22 19:32:25 2014

ENDCOMMENT



NEURON {


  RANGE comp76_Vrest, comp76_V_t, comp77_C, comp78_e_Leak, comp78_gbar_Leak
  RANGE i_Leak

  RANGE e



  RANGE comp78_e_Leak

  NONSPECIFIC_CURRENT i


}



PARAMETER {
  comp78_e_Leak  =  -54.4

  comp78_gbar_Leak  =  0.0003

  comp76_Vrest  =  -65.0

  comp76_V_t  =  -35.0

  comp77_C  =  1.0


}




ASSIGNED {
  v

  i

  e

  i_Leak


}


PROCEDURE asgns () {
  e  =  comp78_e_Leak


}





BREAKPOINT {





  i_Leak  =  comp78_gbar_Leak * (v - comp78_e_Leak)

  i  =  i_Leak


}






