TITLE hodgkin_huxley_K


COMMENT
This file was generated by NEMO (http://wiki.call-cc.org/nemo) version 9.0 on Mon Sep 22 19:32:25 2014

ENDCOMMENT



NEURON {


  RANGE comp49_Vrest, comp49_V_t, comp50_C, comp51_gbar_K, comp51_e_K, K_m61
  RANGE i_K

  RANGE ik, ek



  RANGE comp51_e_K

  USEION k READ ek WRITE ik 


}

FUNCTION comp51_bnf (v) {

  comp51_bnf  =  0.125 * exp(-(v + 65.0) / 80.0)

}  

FUNCTION comp51_anf (v) {

  comp51_anf  =  0.01 * (v + 55.0) / (1.0 + -(exp(-(v + 55.0) / 10.0)))

}  



PARAMETER {
  comp49_V_t  =  -35.0

  comp51_e_K  =  -77.0

  comp49_Vrest  =  -65.0

  comp50_C  =  1.0

  comp51_gbar_K  =  0.036


}



STATE {
  K_m61C

  K_m61O

  K_m61


}



ASSIGNED {
  v

  ik

  ek

  i_K


}


PROCEDURE asgns () {
  ek  =  comp51_e_K


}



PROCEDURE reactions () {
  K_m61  =  K_m61O


}




BREAKPOINT {

  SOLVE states METHOD cnexp



   reactions()

  i_K  =  (comp51_gbar_K * K_m61 ^ 4.0) * (v - comp51_e_K)

  ik  =  i_K


}
DERIVATIVE states {
  LOCAL v86


  asgns()


  v86  =  K_m61O
                            K_m61O'  =  (1.0 - v86) * (comp51_anf(v)) - K_m61O * comp51_bnf(v)


}






INITIAL {


  asgns()

	  
  K_m61  = 
                            (comp51_anf(comp49_Vrest)) /
                            (comp51_anf(comp49_Vrest) + comp51_bnf(comp49_Vrest))

  K_m61O  =  K_m61


	  


	  
}



