TITLE hodgkin_huxley_Na


COMMENT
This file was generated by NEMO (http://wiki.call-cc.org/nemo) version 9.0 on Mon Sep 22 19:32:25 2014

ENDCOMMENT



NEURON {


  RANGE comp19_Vrest, comp19_V_t, comp20_C, comp21_e_Na, comp21_gbar_Na, Na_m33, Na_h34
  RANGE i_Na

  RANGE ina, ena



  RANGE comp21_e_Na

  USEION na READ ena WRITE ina 


}

FUNCTION comp21_bmf (v) {

  comp21_bmf  =  4.0 * exp(-(v + 65.0) / 18.0)

}  

FUNCTION comp21_bhf (v) {

  comp21_bhf  =  1.0 / (1.0 + exp(-(v + 35.0) / 10.0))

}  

FUNCTION comp21_amf (v) {

  comp21_amf  =  0.1 * (v + 40.0) / (1.0 + -(exp(-(v + 40.0) / 10.0)))

}  

FUNCTION comp21_ahf (v) {

  comp21_ahf  =  0.07 * exp(-(v + 65.0) / 20.0)

}  



PARAMETER {
  comp21_e_Na  =  50.0

  comp21_gbar_Na  =  0.12

  comp19_V_t  =  -35.0

  comp19_Vrest  =  -65.0

  comp20_C  =  1.0


}



STATE {
  Na_m33C

  Na_m33O

  Na_h34C

  Na_h34O

  Na_m33

  Na_h34


}



ASSIGNED {
  v

  ina

  ena

  i_Na


}


PROCEDURE asgns () {
  ena  =  comp21_e_Na


}



PROCEDURE reactions () {
  Na_m33  =  Na_m33O

  Na_h34  =  Na_h34O


}




BREAKPOINT {

  SOLVE states METHOD cnexp



   reactions()

  i_Na  =  (comp21_gbar_Na * Na_m33 ^ 3.0 * Na_h34) * (v - comp21_e_Na)

  ina  =  i_Na


}
DERIVATIVE states {
  LOCAL v82, v84


  asgns()


  v82  =  Na_h34O
                          Na_h34O'  =  (1.0 - v82) * (comp21_ahf(v)) - Na_h34O * comp21_bhf(v)

  v84  =  Na_m33O
                          Na_m33O'  =  (1.0 - v84) * (comp21_amf(v)) - Na_m33O * comp21_bmf(v)


}






INITIAL {


  asgns()

	  
  Na_h34  = 
                          (comp21_ahf(comp19_Vrest)) /
                          (comp21_ahf(comp19_Vrest) + comp21_bhf(comp19_Vrest))

  Na_h34O  =  Na_h34

  Na_m33  = 
                                        (comp21_amf(comp19_Vrest)) /
                                        (comp21_amf(comp19_Vrest) + comp21_bmf(comp19_Vrest))

  Na_m33O  =  Na_m33


	  


	  
}



